### ISSUE TITLE
UglifyJs: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by waif1989** [kevva/astral-regex#2]
Hello,when I build my project with webpack using production mode.The 'UglifJs' plugin will print error message 'Unexpected token: operator (>)'.When I read 'astral-regex' code,I find that script using ES6 syntax.In the mean while my webpack.config.js set property 'exclude' to 'node_modules' like most people do.The error will happen.So I want to suggest 'astral-regex' main script compiles ES6 syntax before exports. :-)

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by waif1989** [comment]
Thank for answering my question. :-) Actually, following your steps or I remove the 'node_modules' in the array of property  'exclude' which be defined in my webpack.config.js can solving this problem. I think 'astral-regex'  is really good and useful, if this package is compatible with Node.js and Browser as defaulted will be more better.
